### ISSUE TITLE
Position and width of the context menu

### ISSUE THREAD

**Issue by Elioravr** [vkbansal/react-contextmenu#45]
I'm trying to customize the design of the context menu when it gets to the sides of the screen. Currently what's happening is that the menu shrinks (it's width get smaller and the text gets down):

Here is what it looks like when the position is ok:
![screen shot 2016-11-21 at 15 27 03](https://cloud.githubusercontent.com/assets/1877192/20484254/05d030c6-afff-11e6-9059-42971279f870.png)
Here is what it looks like when the position is too right:
![screen shot 2016-11-21 at 15 26 55](https://cloud.githubusercontent.com/assets/1877192/20484255/05da54de-afff-11e6-93fe-91c6191beef4.png)

I'd like to make it behave like the regular context menu of the computer (the width doesn't change, but the position is - I can't take a screenshot of it because the mouse is not included in the screenshots, but you can try it yourself).

Is there any way to make it act as I expect?

**Comment by vkbansal** [comment]
Can you share the CSS code?

**Comment by Elioravr** [comment]
That's the thing.. I added no css referring the position or the width..

Here is the relevant css:

```css
.react-contextmenu-wrapper {
  text-align: right;
}

.react-contextmenu {
  display: none;
}

.react-contextmenu--visible {
  display: block;
  margin: 0;
  padding: 3px 0 4px;
  background: rgba(240, 240, 240, 0.95);
  box-shadow: 0px 8px 15px rgba(0, 0, 0, 0.2);
  border-radius: 4px;
  font-family: Lucida Grande;
  font-size: 14px;
  line-height: 15px;
  border: 1px solid rgba(0, 0, 0, 0.10);
  padding: 5px 0;
}

.react-contextmenu-item {
  padding: 3px 10px;
  padding: 0 20px;
  border-top: 1px solid rgba(0, 0, 0, 0);
  border-bottom: 1px solid rgba(0, 0, 0, 0);
}
```
